[2024-05-03T10:46:31.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T10:46:31.295+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tutorial_objectstorage.get_air_quality_data manual__2024-05-03T10:46:27.527204+00:00 [queued]>
[2024-05-03T10:46:31.300+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tutorial_objectstorage.get_air_quality_data manual__2024-05-03T10:46:27.527204+00:00 [queued]>
[2024-05-03T10:46:31.301+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-03T10:46:31.311+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): get_air_quality_data> on 2024-05-03 10:46:27.527204+00:00
[2024-05-03T10:46:31.316+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-03T10:46:31.318+0000] {standard_task_runner.py:63} INFO - Started process 174 to run task
[2024-05-03T10:46:31.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tutorial_objectstorage', 'get_air_quality_data', 'manual__2024-05-03T10:46:27.527204+00:00', '--job-id', '7', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/tutorial_objectstorage.py', '--cfg-path', '/tmp/tmp7gkzdho1']
[2024-05-03T10:46:31.320+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask get_air_quality_data
[2024-05-03T10:46:31.352+0000] {task_command.py:426} INFO - Running <TaskInstance: tutorial_objectstorage.get_air_quality_data manual__2024-05-03T10:46:27.527204+00:00 [running]> on host 55edbf8b0e5d
[2024-05-03T10:46:31.415+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tutorial_objectstorage' AIRFLOW_CTX_TASK_ID='get_air_quality_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T10:46:27.527204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T10:46:27.527204+00:00'
[2024-05-03T10:46:31.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T10:46:33.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T10:46:33.066+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 262, in fs
    return self._fs_cached
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 436, in __getattr__
    raise AttributeError(item)
AttributeError: _fs_cached. Did you mean: '_hash_cached'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/fs/s3.py", line 50, in get_fs
    from s3fs import S3FileSystem
ModuleNotFoundError: No module named 's3fs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 94, in get_air_quality_data
    base.mkdir(exist_ok=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/implementations/cloud.py", line 48, in mkdir
    super().mkdir(mode=mode, parents=parents, exist_ok=exist_ok)
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 914, in mkdir
    self.fs.mkdir(
    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 264, in fs
    fs = self._fs_cached = self._fs_factory(
                           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/path.py", line 77, in _fs_factory
    return attach(protocol or "file", storage_options.get("conn_id")).fs
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/store/__init__.py", line 61, in fs
    return get_fs(self.protocol, self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/__init__.py", line 109, in get_fs
    return fs(conn_id, options)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/fs/s3.py", line 52, in get_fs
    raise ImportError(
ImportError: Airflow FS S3 protocol requires the s3fs library, but it is not installed as it requiresaiobotocore. Please install the s3 protocol support library by running: pip install apache-airflow-providers-amazon[s3fs]
[2024-05-03T10:46:33.078+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=tutorial_objectstorage, task_id=get_air_quality_data, execution_date=20240503T104627, start_date=20240503T104631, end_date=20240503T104633
[2024-05-03T10:46:33.090+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task get_air_quality_data (Airflow FS S3 protocol requires the s3fs library, but it is not installed as it requiresaiobotocore. Please install the s3 protocol support library by running: pip install apache-airflow-providers-amazon[s3fs]; 174)
[2024-05-03T10:46:33.137+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T10:46:33.148+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T10:46:33.151+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
